#!/bin/sh
set -ex

###
# Install azure metrics exporter
###
mkdir -p /opt/azure_metrics_exporter
mv /resources/azure_metrics_exporter /opt/azure_metrics_exporter/

adduser -S -h /opt/azure_metrics_exporter exporter

chown -R exporter /opt/azure_metrics_exporter

###
# CIS Hardening
###
touch /etc/login.defs
chmod 0444 /etc/login.defs
chmod 0600 /etc/shadow
